import PDFDocument from "pdfkit";
import { attendance } from "../database/attendance.model.js";

export const downloadAttendancePdf = async (req, res) => {
  try {
    const adminId = req.user?.id;
    if (!adminId) {
      return res.status(401).json({
        success: false,
        message: "Admin authentication required",
      });
    }

    const attendanceRecords = await attendance
      .find({ admin: adminId })
      .sort({ date: -1 });

    if (!attendanceRecords.length) {
      return res
        .status(404)
        .json({ success: false, message: "No attendance record found" });
    }

    const doc = PDFDocument({
      size: "A4",
      margin: 30,
    });

    const pdfChunks = [];
    const pdfReady = new Promise((resolve, reject) => {
      doc.on("data", (chunk) => pdfChunks.push(chunk));
      doc.once("end", resolve);
      doc.once("error", reject);
    });

    doc.fontSize(20).font("Helvetica-Bold").text("ATTENDANCE REPORT", {
      align: "center",
    });

    doc.moveDown();
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Generated: ${new Date().toLocaleString("en-IN")}`, {
        align: "center",
      });

    doc.moveDown(2);
    const total = attendanceRecords.length;

    const present = attendanceRecords.filter(
      (item) => item.status === "Present",
    ).length;

    const absent = attendanceRecords.filter(
      (item) => item.status === "Absent",
    ).length;

    const matched = attendanceRecords.filter((item) => item.matched).length;

    const failed = attendanceRecords.filter((item) => !item.matched).length;

    doc.fontSize(12).font("Helvetica-Bold");

    doc.text(`Total Records: ${total}`);
    doc.text(`Present: ${present}`);
    doc.text(`Absent: ${absent}`);
    doc.text(`Matched: ${matched}`);
    doc.text(`Failed: ${failed}`);

    doc.moveDown(2);

    const rows = attendanceRecords.map((item) => [
      item.name || "Unknown",
      item.date ? new Date(item.date).toLocaleDateString("en-IN") : "-",
      item.time || "-",
      item.status || "-",
      item.matched ? "Matched" : "Failed",
      `${((item.confidence || 0) * 100).toFixed(2)}%`,
    ]);

    const columns = [
      { label: "Name", width: 150 },
      { label: "Date", width: 75 },
      { label: "Time", width: 65 },
      { label: "Status", width: 75 },
      { label: "Matched", width: 85 },
      { label: "Confidence", width: 85 },
    ];
    const rowHeight = 18;
    const tableLeft = 30;

    const drawTableHeader = () => {
      let x = tableLeft;
      doc.font("Helvetica-Bold").fontSize(8);
      for (const column of columns) {
        doc.text(column.label, x, doc.y, {
          width: column.width,
          height: rowHeight,
          lineBreak: false,
        });
        x += column.width;
      }
      doc
        .moveTo(tableLeft, doc.y + 2)
        .lineTo(565, doc.y + 2)
        .stroke();
      doc.moveDown(0.5);
    };

    drawTableHeader();
    doc.font("Helvetica").fontSize(8);
    for (const row of rows) {
      if (doc.y + rowHeight > 760) {
        doc.addPage();
        drawTableHeader();
        doc.font("Helvetica").fontSize(8);
      }

      const rowTop = doc.y;
      let x = tableLeft;
      row.forEach((value, index) => {
        doc.text(String(value), x, rowTop, {
          width: columns[index].width,
          height: rowHeight,
          lineBreak: false,
          ellipsis: true,
        });
        x += columns[index].width;
      });
      doc.y = rowTop + rowHeight;
    }

    doc.moveDown();

    doc.fontSize(8).text("Generated by Attendance Management System", {
      align: "center",
    });

    doc.end();
    await pdfReady;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="Attendance_Report.pdf"`,
    );
    res.end(Buffer.concat(pdfChunks));
  } catch (error) {
    console.error("PDF Error:", error);

    if (!res.headersSent) {
      return res.status(500).json({
        success: false,
        message: `Failed to generate PDF: ${error.message}`,
      });
    }
  }
};
