import PDFDocument from "pdfkit";
import "pdfkit-table";
import { attendance } from "../database/attendance.model.js";

export const downloadAttendancePdf = async (req, res) => {
  try {
    const attendanceRecords = await attendance
      .find({ admin: req.user.id })
      .sort({ date: -1 });

    if (!attendanceRecords.length) {
      return res
        .status(404)
        .json({ success: false, message: "No attendance record found" });
    }

    const doc = PDFDocument({
      size: "A4",
      margin: 30,
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="Attendance_Report.pdf"`,
    );

    doc.pipe(res);
    doc.fontSize(20).font("Helvetica-Bold").text("ATTENDANCE REPORT", {
      align: "center",
    });

    doc.moveDown();
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Generated: ${new Date().toLocaleString("en-IN")}`, {
        align: "center",
      });

    doc.moveDown(2);
    const total = attendanceRecords.length;

    const present = attendanceRecords.filter(
      (item) => item.status === "Present",
    ).length;

    const absent = attendanceRecords.filter(
      (item) => item.status === "Absent",
    ).length;

    const matched = attendanceRecords.filter((item) => item.matched).length;

    const failed = attendanceRecords.filter((item) => !item.matched).length;

    doc.fontSize(12).font("Helvetica-Bold");

    doc.text(`Total Records: ${total}`);
    doc.text(`Present: ${present}`);
    doc.text(`Absent: ${absent}`);
    doc.text(`Matched: ${matched}`);
    doc.text(`Failed: ${failed}`);

    doc.moveDown(2);

    const rows = attendanceRecords.map((item) => [
      item.name || "Unknown",
      item.date ? new Date(item.date).toLocaleDateString("en-IN") : "-",
      item.time || "-",
      item.status || "-",
      item.matched ? "Matched" : "Failed",
      `${((item.confidence || 0) * 100).toFixed(2)}%`,
    ]);

    await doc.table({
      headers: ["Name", "Date", "Time", "Status", "Matched", "Confidence"],

      rows,

      options: {
        width: 535,
        padding: 5,
        prepareHeader: () => {
          doc.font("Helvetica-Bold").fontSize(8);
        },
        prepareRow: () => {
          doc.font("Helvetica").fontSize(8);
        },
      },
    });

    doc.moveDown();

    doc.fontSize(8).text("Generated by Attendance Management System", {
      align: "center",
    });

    doc.end();
  } catch (error) {
    console.error("PDF Error:", error);

    if (!res.headersSent) {
      return res.status(500).json({
        success: false,
        message: "Failed to generate PDF",
      });
    }
  }
};
